services:
  - type: web
    name: aro-colombia
    env: node
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
